### ISSUE TITLE
FiraCode.zip VERIFY FAILED

### ISSUE THREAD

**Issue by markfswe** [cova-fe/cova-overlay#1]
Hi there! Thank you for your overlay.

I tried to emerge nerd-fonts 3 using your ebuild but get this error:
```
!!! Fetched file: FiraCode.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      21988557
!!! Expected: 76490798
Refetching... File renamed to '/var/cache/distfiles/FiraCode.zip._checksum_failure_.le1l7wnx'

!!! Couldn't download 'FiraCode.zip'. Aborting.
 * Fetch failed for 'media-fonts/nerd-fonts-3.0.0', Log file:
 *  '/var/tmp/portage/media-fonts/nerd-fonts-3.0.0/temp/build.log'
```

Use flags: `firacode`

**Comment by ekhodx** [comment]
Without this flag everything works fine. Personally I use fira code in my terminal but maybe I don't even need this use flag. I am not sure

**Comment by cova-fe** [comment]
My fault, it seems that some files from an old release got included. On it.
