### ISSUE TITLE
dev-vcs/lazygit should have dev-go/gox as a --build time--  dependency

### ISSUE THREAD

**Issue by kenshin33** [cova-fe/cova-overlay#3]
straight after enabling and synchin the overlay 
emerge lazygit fails with this as the error:

/var/tmp/portage/dev-vcs/lazygit-0.40.2/temp/environment: line 1405: gox: command not found
 * ERROR: dev-vcs/lazygit-0.40.2::cova failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 136:  Called src_compile
 *   environment, line 1405:  Called die
 * The specific snippet of code:
 *       gox -os=$(go env GOOS) -arch=$(go env GOARCH) -output lazygit -ldflags "-X main.version=${PV} -X main.date=$(date -I -u) -X main.commit=${BUILD_COMMIT} -X main.buildSource=${BUILD_SOURCE}" -verbose . || die
 * 
 * If you need support, post the output of `emerge --info '=dev-vcs/lazygit-0.40.2::cova'`,
 * the complete build log and the output of `emerge -pqv '=dev-vcs/lazygit-0.40.2::cova'`.
 * The complete build log is located at '/var/tmp/portage/dev-vcs/lazygit-0.40.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-vcs/lazygit-0.40.2/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-vcs/lazygit-0.40.2/work/lazygit-0.40.2'
 * S: '/var/tmp/portage/dev-vcs/lazygit-0.40.2/work/lazygit-0.40.2'

**Comment by cova-fe** [comment]
Right you are. on it, thanks!
